### ISSUE TITLE
Running allure in maven plugin

### ISSUE THREAD

**Issue by trjo1016** [uchagani/allure-playwright-java#4]
Hello everyone,

I am currently trying to show my test results in Allure and to my understanding it works like this:

1. Declare dependency similar to the README
2. Install Allure locally
3. Run tests
4. allure serve <resultsDirectory>

For some reason, Allure can't generate the "allure-results" folder or similar folders, so I can't run allure serve on that folder. Is my procedure correct, or how can you generate reports out of playwright java?

**Comment by trjo1016** [comment]
Here's my POM.xml (shortened)
`<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <packaging>pom</packaging>

    <properties>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <junit.version>5.8.2</junit.version>
        <google.code.gson.version>2.9.0</google.code.gson.version>
 
        <org.apache.maven.source-plugins>3.1.0</org.apache.maven.source-plugins>
        <org.apache.maven.failsafe-plugins>2.19</org.apache.maven.failsafe-plugins>
        <org.junit.platform.surefire-provider>1.0.0</org.junit.platform.surefire-provider>
        <org.junit.platform.surefire-plugin>2.19.1</org.junit.platform.surefire-plugin>

        <org.mockito.mockito-core>3.3.3</org.mockito.mockito-core>
        <skip.unit.tests>false</skip.unit.tests>
        <skip.integration.tests>true</skip.integration.tests>

        
        <playwright.version>1.27.1</playwright.version>

        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
    </properties>

    <dependencyManagement>
        <dependencies>

            <dependency>
                <groupId>org.junit.jupiter</groupId>
                <artifactId>junit-jupiter-api</artifactId>
                <version>${junit.version}</version>
                <scope>test</scope>
            </dependency>


            <dependency>
                <groupId>org.junit.jupiter</groupId>
                <artifactId>junit-jupiter-engine</artifactId>
                <version>${junit.version}</version>
                <scope>test</scope>
            </dependency>

            <dependency>
                <groupId>org.junit.jupiter</groupId>
                <artifactId>junit-jupiter-params</artifactId>
                <version>${junit.version}</version>
                <scope>test</scope>
            </dependency>

            <dependency>
                <groupId>org.junit.vintage</groupId>
                <artifactId>junit-vintage-engine</artifactId>
                <version>${junit.version}</version>
                <scope>test</scope>
            </dependency>

            <dependency>
                <groupId>org.mockito</groupId>
                <artifactId>mockito-core</artifactId>
                <version>${org.mockito.mockito-core}</version>
                <scope>test</scope>
            </dependency>

            
            
            <dependency>
                <groupId>org.spockframework</groupId>
                <artifactId>spock-core</artifactId>
                <version>${spock.version}</version>
                <scope>test</scope>
            </dependency>

            <dependency>
                <groupId>com.microsoft.playwright</groupId>
                <artifactId>playwright</artifactId>
                <version>${playwright.version}</version>
            </dependency>

            <dependency>
                <groupId>io.github.uchagani</groupId>
                <artifactId>allure-playwright-java</artifactId>
                <version>1.1.0</version>
            </dependency>

        </dependencies>
    </dependencyManagement>
    <profiles>
        <profile>
            <id>prometheus-build</id>
            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>
        </profile>
        <profile>
            <id>prometheus-demo</id>
        </profile>
        <profile>
            <id>prometheus-integration-tests</id>
            <properties>
                <skip.integration.tests>false</skip.integration.tests>
                <skip.unit.tests>true</skip.unit.tests>
            </properties>
        </profile>
    </profiles>
    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <version>${org.junit.platform.surefire-plugin}</version>
                    <dependencies>
                        <dependency>
                            <groupId>org.junit.platform</groupId>
                            <artifactId>junit-platform-surefire-provider</artifactId>
                            <version>${org.junit.platform.surefire-provider}</version>
                        </dependency>
                    </dependencies>
                    <configuration>
                        <testFailureIgnore>true</testFailureIgnore>
                        <skipTests>${skip.unit.tests}</skipTests>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-failsafe-plugin</artifactId>
                    <version>${org.apache.maven.failsafe-plugins}</version>
                    <executions>
                        <execution>
                            <id>integration-test</id>
                            <goals>
                                <goal>integration-test</goal>
                            </goals>
                        </execution>
                        <execution>
                            <id>verify</id>
                            <goals>
                                <goal>verify</goal>
                            </goals>
                        </execution>
                    </executions>
                    <configuration>
                        <skipITs>${skip.integration.tests}</skipITs>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-source-plugin</artifactId>
                    <version>${org.apache.maven.source-plugins}</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-site-plugin</artifactId>
                    <version>3.7.1</version>
                </plugin>
                <plugin>
                    <groupId>org.codehaus.groovy.maven</groupId>
                    <artifactId>gmaven-plugin</artifactId>
                    <version>1.0</version>
                    <extensions>true</extensions>
                    <executions>
                        <execution>
                            <goals>
                                <goal>testCompile</goal>
                            </goals>
                            <configuration>
                                <sources>
                                    <fileset>
                                        <directory>${pom.basedir}/src/test/java</directory>
                                        <includes>
                                            <include>**/*.groovy</include>
                                        </includes>
                                    </fileset>
                                </sources>
                            </configuration>
                        </execution>
                    </executions>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>
</project>`

**Comment by trjo1016** [comment]
also SideNote:
Allure CLI /Allure Commandline version 2.4.1 (in your pom.xml) is not available anymore in bintray (where it is supposed to extract from). Allure 2 moved everything to maven-central, please update your pom and use `<reportVersion>2.18.1</reportVersion>` as an example. other versions are found here: 

https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/

you may need to add another configuration under `<reportVersion>`: 
`<allureDownloadUrl>https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/%s/allure-commandline-%s.zip</allureDownloadUrl>`

%s for version

**Comment by uchagani** [comment]
@trjo1016 the allure command line should be installed separately.  [Please see the Allure documentation about command line](https://docs.qameta.io/allure-report/#_installing_a_commandline).  

Also, it seems you're using junit 4 but I don't see you installing junit 4 allure.  [Please see the Allure docs for Junit 4.](https://docs.qameta.io/allure-report/#_junit_4).

You also haven't configured your surefire plugin as Allure requires.  The docs above for junit show what needs to be added to to the surefire plugin in pom.xml to get it working.

Once you have done all of this, then all you need to do is add this library as a dependency.

**Comment by trjo1016** [comment]
ok, I will try it to adjust my pom.xml and come back later.

**Comment by trjo1016** [comment]
ok, I will try it to adjust my pom.xml and come back later.
once I have run the test, should I call the serve/report command over CLI or with Maven mvn?

**Comment by uchagani** [comment]
@trjo1016 going to close this for now, please create a new issue with more information if you still have problems getting this to work.
