### ISSUE TITLE
Ability to mask parameters

### ISSUE THREAD

**Issue by CrepeClown** [uchagani/allure-playwright-java#6]
Currently Allure features the ability to mask passwords in reports by doing the following:

```
@Step("Log in to Application Username - {username}")
    public AppPage loginUser(@Param("username") String username, @Param(name="password", mode=MASKED) String password){
        page.fill(txtUsername, username);
        page.fill(txtPassword, password);
        page.click(btnLogon);
```

On the report it will show the password as:

![image](https://user-images.githubusercontent.com/87724613/202571472-5376fbf4-1de3-46ca-8a3b-4627d08953c1.png)

However, the auto-generated step from allure-playwright-java will still display the password(orange box). Is this something that might work with your library?

**Comment by uchagani** [comment]
Allure's masking works off of annotating the methods themselves and not the method call.

It may be possible to do what you want but you would have to wrap every call to locator/page methods yourself.

Unfortunately this is out of the scope of this library.
